package com.darkfactory.plantpotting.identify

import com.google.common.truth.Truth.assertThat
import org.junit.Test
import kotlin.coroutines.Continuation

/**
 * Locks the PLANTPOTTING-0001 §4.1 seam: the `PlantIdentifier` interface block must remain
 * byte-for-byte stable, and `IdentificationResult` may only grow additive default fields.
 *
 * Failing this test is a sprint-blocker bug. See PLANTPOTTING-0003 §0.4 / §4.4.
 *
 * Uses java reflection so the test compiles against the JVM-target classpath without
 * needing kotlin-reflect, and fails RED at runtime until PLANTPOTTING-0003 §3.1 lands
 * the additive `lowConfidence` field on `IdentificationResult`.
 */
class PlantIdentifierContractTest {
    @Test
    fun plantIdentifierExposesExactlyOneIdentifyMethodCompiledAsSuspend() {
        val methods = PlantIdentifier::class.java.declaredMethods
        assertThat(methods).hasLength(1)

        val identify = methods.single()
        assertThat(identify.name).isEqualTo("identify")

        // suspend functions are compiled with a trailing Continuation arg.
        val params = identify.parameterTypes
        assertThat(params).hasLength(2)
        assertThat(params[0]).isEqualTo(ByteArray::class.java)
        assertThat(Continuation::class.java.isAssignableFrom(params[1])).isTrue()

        // suspend return type at JVM level is Object (Any?). The kotlin-reflect-free
        // way to confirm it's still a "returns IdentificationResult or COROUTINE_SUSPENDED"
        // shape is to verify the Java return type is Object (kotlin.Any!) — same as before.
        assertThat(identify.returnType).isEqualTo(Object::class.java)
    }

    @Test
    fun identificationResultHasSpeciesIdDisplayNameSourceAndLowConfidence() {
        val klass = IdentificationResult::class.java
        // Component property accessors on a data class follow the `componentN()` naming.
        // The simpler check: confirm the data-class properties via their getter methods,
        // which mirror the property names.
        val getterNames =
            klass.declaredMethods
                .filter { it.name.startsWith("get") && it.parameterCount == 0 }
                .map { it.name.removePrefix("get").replaceFirstChar { c -> c.lowercaseChar() } }
                .toSet()
        assertThat(getterNames).containsAtLeast(
            "speciesId",
            "displayName",
            "source",
            "lowConfidence",
        )
    }

    @Test
    fun identificationResultLowConfidenceIsPresentAndDefaultsFalse() {
        // The data class generated by `data class IdentificationResult(...val lowConfidence: Boolean = false)`
        // exposes a default-bearing synthetic constructor on the JVM and a `getLowConfidence()` getter.
        // Reading the default through reflection requires invoking the default-aware synthetic
        // constructor — too fragile. Instead, construct using the *primary* constructor that
        // includes lowConfidence: pass the three legacy args + `false` explicitly, and confirm
        // both the property exists and reads back as false.
        val klass = IdentificationResult::class.java
        val ctor =
            klass.declaredConstructors
                .filter { it.parameterCount == 4 }
                .firstOrNull()
                ?: error(
                    "IdentificationResult has no 4-arg constructor — the additive `lowConfidence` " +
                        "field has not landed yet. See PLANTPOTTING-0003 §3.1.",
                )
        // Argument order is the declared property order.
        val sample = ctor.newInstance("x", "Y", IdSource.ON_DEVICE_MODEL, false)
        val getter = klass.getMethod("getLowConfidence")
        val value: Any? = getter.invoke(sample)
        assertThat(value as Boolean?).isFalse()
    }

    @Test
    fun idSourceContainsStubAndOnDeviceAndCloudVariants() {
        val names = IdSource.values().map { it.name }.toSet()
        assertThat(names).containsAtLeast(
            "STUB_DETERMINISTIC",
            "STUB_RANDOM",
            "ON_DEVICE_MODEL",
            "CLOUD",
        )
    }
}
