package com.darkfactory.plantpotting.identify

import com.google.common.truth.Truth.assertThat
import org.junit.Test
import java.io.File

/**
 * Phase-1 dep audit (PLANTPOTTING-0003 §1.2 / §1.4). Two complementary assertions:
 *
 * 1. **TFLite is on the release runtime classpath** — proved by reading the audit file
 *    that the `verifyNoNetworking` Gradle task writes under `build/verify-no-networking/`.
 *    Fails RED before §1.3 wires `org.tensorflow:tensorflow-lite{,-support}` into
 *    `dependencies { implementation(...) }`.
 *
 * 2. **No forbidden networking transitive snuck in via TFLite.** Allowlist matches the
 *    narrow §7.4 list (`okhttp`, `retrofit`, `firebase`, `play-services-network`, `volley`,
 *    `ktor-client-okhttp`). `play-services-tasks` is the Tasks API and is *not* networking.
 *
 * The audit file is regenerated by `:app:verifyNoNetworking`. Tests should run after
 * that task (the `check` lifecycle wires it in), but to keep this unit test self-contained
 * we degrade with an informative message if the file is missing.
 */
class VerifyNoNetworkingRegressionTest {
    private val auditFile: File = File("build/verify-no-networking/release-runtime-deps.txt")

    private val forbiddenNeedles =
        listOf(
            "okhttp",
            "retrofit",
            "firebase",
            "play-services-network",
            "volley",
            "ktor-client-okhttp",
        )

    private fun deps(): List<String> {
        if (!auditFile.exists()) {
            error(
                "verifyNoNetworking audit file missing at ${auditFile.absolutePath}. " +
                    "Run `./gradlew verifyNoNetworking` first to regenerate.",
            )
        }
        return auditFile.readLines().filter { it.isNotBlank() }
    }

    @Test
    fun tensorflowLiteIsOnReleaseRuntimeClasspath() {
        val coords = deps()
        val tfliteCoords = coords.filter { it.startsWith("org.tensorflow:tensorflow-lite") }
        // Expect at least `org.tensorflow:tensorflow-lite` and `org.tensorflow:tensorflow-lite-support`.
        assertThat(tfliteCoords).contains("org.tensorflow:tensorflow-lite")
        assertThat(tfliteCoords).contains("org.tensorflow:tensorflow-lite-support")
    }

    @Test
    fun noForbiddenNetworkingDepsOnReleaseRuntimeClasspath() {
        val coords = deps()
        val bad =
            coords.filter { coord ->
                forbiddenNeedles.any { needle -> coord.lowercase().contains(needle) }
            }
        assertThat(bad).isEmpty()
    }

    @Test
    fun playServicesTasksIsNotTreatedAsNetworking() {
        // Defensive: if TFLite Support ever pulls in play-services-tasks (the coroutine/promise
        // Tasks API, not networking), the §7.4 allowlist must still treat it as benign. This
        // test documents the deliberate non-match.
        val sample = "com.google.android.gms:play-services-tasks"
        val matched = forbiddenNeedles.any { sample.lowercase().contains(it) }
        assertThat(matched).isFalse()
    }
}
